version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=serge
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=library
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  app:
    image: 'openjdk:17-alpine'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library
      - SPRING_DATASOURCE_USERNAME=serge
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  pgdata: